version: '3'

services:
  libra-server:
    depends_on:
      - postgres
    build: .
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_DB=libra-test
      - POSTGRES_USER=libra
      - POSTGRES_PASSWORD=password
